name = "Jessica Acosta"
description = "Accomplished Real Estate Broker, captivating with versatility and charisma."
keywords = "Jessica Acosta, Realtor, Broker, Space Coast, Acosta Realty, Florida"
image = "jessica.webp"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-XLJ81DCZFV"
base_url = "https://jessicaacostarealtor.github.io/"

[[sections]]
title = "Contact"
description = "Contact me one of these ways"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/minutemailer/ffffff"
title = "Email"
url = "mailto:jessica@AcostaRealtyFL.com"
[[sections.items]]
icon = "https://cdn.simpleicons.org/apple/ffffff"
title = "Call"
url = "tel:+14077290337"
[[sections.items]]
icon = "https://cdn.simpleicons.org/imessage/ffffff"
title = "SMS"
url = "sms:+14077290337"


#[[sections]]
#title = "Movies"
#description = "Here are some of my movies"
#direction = "column"
#item_style = "outline"
#[[sections.items]]
#embed_url = "https://www.youtube.com/embed/x0gUY9ddjQY"
#[[sections.items]]
#title = "Nightcrawler"
#description = "A mesmerizing thriller delving into the dark world of crime journalism"
#url = "https://www.imdb.com/title/tt2872718/"
#[[sections.items]]
#title = "Brokeback Mountain"
#description = "A groundbreaking romantic drama challenging societal expectations"
#url = "https://www.imdb.com/title/tt0388795/"
#[[sections.items]]
#title = "Prisoners"
#description = "A gripping thriller entangling a detective in a web of secrets during a kidnapping investigation"
#url = "https://www.imdb.com/title/tt1392214/"
